/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ccebc7",
        outline: "#72796e",
        "surface-variant": "#e3e3de",
        "on-background": "#1a1c19",
        "surface-tint": "#3b6934",
        "inverse-on-surface": "#f1f1ec",
        "on-surface": "#1a1c19",
        "on-primary-container": "#9dd090",
        tertiary: "#3a3935",
        "surface-container": "#eeeee9",
        "surface-container-highest": "#e3e3de",
        "on-tertiary-container": "#c5c2bc",
        "tertiary-fixed-dim": "#c9c6c0",
        "tertiary-fixed": "#e5e2db",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#334d33",
        "primary-fixed": "#bcf0ae",
        "surface-container-high": "#e8e8e3",
        "on-tertiary-fixed": "#1c1c18",
        "surface-container-low": "#f4f4ee",
        "error-container": "#ffdad6",
        surface: "#fafaf4",
        "on-secondary-fixed": "#07200b",
        "tertiary-container": "#51504b",
        "primary-container": "#2d5a27",
        "secondary-fixed-dim": "#b0cfad",
        "outline-variant": "#c2c9bb",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#42493e",
        primary: "#154212",
        background: "#fafaf4",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a1d494",
        "on-secondary-container": "#506b4f",
        "on-primary-fixed": "#002201",
        "on-tertiary-fixed-variant": "#474742",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#23501e",
        error: "#ba1a1a",
        "secondary-container": "#ccebc7",
        "surface-bright": "#fafaf4",
        "surface-dim": "#dadad5",
        "inverse-surface": "#2f312e",
        "inverse-primary": "#a1d494",
        "on-primary": "#ffffff",
        secondary: "#4a6549",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "20px",
        "max-width": "1280px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
